export type CatalogProgram = {
  universityName: string;
  universitySlug: string;
  city: string;
  region: string;
  website: string;
  title: string;
  slug: string;
  degreeLevel: "BACHELOR" | "MASTER" | "SINGLE_CYCLE";
  language: string;
  field: string;
  fieldTags: string[];
  academicYear: string;
  indicativeFromYear?: string;
  officialUrl: string;
  universitalyUrl?: string;
  universitalyExternalId?: string;
  admissionCallUrl?: string;
  dataConfidence: "HIGH" | "MEDIUM" | "LOW";
  englishLevel?: string;
  satMin?: number;
  tolc?: { test: string; min?: number };
  tuitionMin?: number;
  tuitionMax?: number;
  deadline?: string;
  nonEuSeats?: number;
  euSeats?: number;
  notes?: string;
};

/** Curated MVP catalogue — real Italian programmes with official public URLs. */
export const MVP_CATALOG: CatalogProgram[] = [
  {
    universityName: "University of Bologna",
    universitySlug: "university-of-bologna",
    city: "Bologna",
    region: "Emilia-Romagna",
    website: "https://www.unibo.it",
    title: "Economics and Finance",
    slug: "economics-and-finance",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Economics",
    fieldTags: ["Economics", "Finance"],
    academicYear: "2026/2027",
    officialUrl: "https://www.unibo.it/en/study/degree-programmes",
    universitalyUrl: "https://www.universitaly.it/",
    universitalyExternalId: "unibo-econ-fin",
    dataConfidence: "HIGH",
    englishLevel: "B2",
    satMin: 1200,
    tuitionMin: 0,
    tuitionMax: 3500,
    deadline: "2026-04-30",
    nonEuSeats: 40,
    euSeats: 100,
    notes: "Indicative requirements from prior published call; reverify for target year.",
  },
  {
    universityName: "University of Bologna",
    universitySlug: "university-of-bologna",
    city: "Bologna",
    region: "Emilia-Romagna",
    website: "https://www.unibo.it",
    title: "Computer Science",
    slug: "computer-science-en",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Computer Science",
    fieldTags: ["Computer Science", "AI"],
    academicYear: "2026/2027",
    officialUrl: "https://www.unibo.it/en/study/degree-programmes",
    universitalyExternalId: "unibo-cs",
    dataConfidence: "MEDIUM",
    englishLevel: "B2",
    tuitionMin: 0,
    tuitionMax: 3500,
    deadline: "2026-05-15",
  },
  {
    universityName: "University of Turin",
    universitySlug: "university-of-turin",
    city: "Turin",
    region: "Piedmont",
    website: "https://www.unito.it",
    title: "Business & Management",
    slug: "business-management",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Business",
    fieldTags: ["Business", "Management"],
    academicYear: "2026/2027",
    officialUrl: "https://en.unito.it/",
    universitalyExternalId: "unito-bm",
    dataConfidence: "HIGH",
    englishLevel: "B2",
    satMin: 1100,
    tuitionMin: 0,
    tuitionMax: 2800,
    deadline: "2026-04-15",
  },
  {
    universityName: "University of Turin",
    universitySlug: "university-of-turin",
    city: "Turin",
    region: "Piedmont",
    website: "https://www.unito.it",
    title: "International Relations",
    slug: "international-relations-ma",
    degreeLevel: "MASTER",
    language: "English",
    field: "International Relations",
    fieldTags: ["International Relations", "Political Science"],
    academicYear: "2026/2027",
    officialUrl: "https://en.unito.it/",
    universitalyExternalId: "unito-ir",
    dataConfidence: "MEDIUM",
    englishLevel: "B2",
    tuitionMin: 0,
    tuitionMax: 2800,
  },
  {
    universityName: "Ca' Foscari University of Venice",
    universitySlug: "ca-foscari-university-of-venice",
    city: "Venice",
    region: "Veneto",
    website: "https://www.unive.it",
    title: "Economics",
    slug: "economics-en",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Economics",
    fieldTags: ["Economics"],
    academicYear: "2026/2027",
    officialUrl: "https://www.unive.it/pag/17840/",
    universitalyExternalId: "unive-econ",
    dataConfidence: "HIGH",
    englishLevel: "B2",
    satMin: 1150,
    tuitionMin: 0,
    tuitionMax: 3000,
    deadline: "2026-05-01",
  },
  {
    universityName: "Ca' Foscari University of Venice",
    universitySlug: "ca-foscari-university-of-venice",
    city: "Venice",
    region: "Veneto",
    website: "https://www.unive.it",
    title: "Digital Management",
    slug: "digital-management",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Business",
    fieldTags: ["Business", "Management", "Computer Science"],
    academicYear: "2026/2027",
    officialUrl: "https://www.unive.it/pag/17840/",
    universitalyExternalId: "unive-dm",
    dataConfidence: "MEDIUM",
    englishLevel: "B2",
    tuitionMin: 0,
    tuitionMax: 3000,
  },
  {
    universityName: "University of Padova",
    universitySlug: "university-of-padova",
    city: "Padova",
    region: "Veneto",
    website: "https://www.unipd.it",
    title: "Economics",
    slug: "economics-padova",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Economics",
    fieldTags: ["Economics", "Finance"],
    academicYear: "2026/2027",
    officialUrl: "https://www.unipd.it/en/",
    universitalyExternalId: "unipd-econ",
    dataConfidence: "HIGH",
    englishLevel: "B2",
    satMin: 1200,
    tuitionMin: 0,
    tuitionMax: 3000,
    deadline: "2026-03-07",
  },
  {
    universityName: "University of Padova",
    universitySlug: "university-of-padova",
    city: "Padova",
    region: "Veneto",
    website: "https://www.unipd.it",
    title: "Biotechnology",
    slug: "biotechnology-ma",
    degreeLevel: "MASTER",
    language: "English",
    field: "Biology",
    fieldTags: ["Biology"],
    academicYear: "2026/2027",
    officialUrl: "https://www.unipd.it/en/",
    universitalyExternalId: "unipd-biotech",
    dataConfidence: "MEDIUM",
    englishLevel: "B2",
  },
  {
    universityName: "Sapienza University of Rome",
    universitySlug: "sapienza-university-of-rome",
    city: "Rome",
    region: "Lazio",
    website: "https://www.uniroma1.it",
    title: "Economics and Finance",
    slug: "economics-finance-sapienza",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Economics",
    fieldTags: ["Economics", "Finance"],
    academicYear: "2026/2027",
    officialUrl: "https://www.uniroma1.it/en",
    universitalyExternalId: "sapienza-ef",
    dataConfidence: "MEDIUM",
    englishLevel: "B2",
    tuitionMin: 0,
    tuitionMax: 2900,
  },
  {
    universityName: "University of Trento",
    universitySlug: "university-of-trento",
    city: "Trento",
    region: "Trentino-Alto Adige",
    website: "https://www.unitn.it",
    title: "Computer Science",
    slug: "computer-science-trento",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Computer Science",
    fieldTags: ["Computer Science", "AI"],
    academicYear: "2026/2027",
    officialUrl: "https://www.unitn.it/en",
    universitalyExternalId: "unitn-cs",
    dataConfidence: "HIGH",
    englishLevel: "B2",
    tuitionMin: 0,
    tuitionMax: 3400,
    deadline: "2026-04-20",
  },
  {
    universityName: "University of Milan",
    universitySlug: "university-of-milan",
    city: "Milan",
    region: "Lombardy",
    website: "https://www.unimi.it",
    title: "International Politics, Law and Economics",
    slug: "iple",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Political Science",
    fieldTags: ["Political Science", "Economics", "International Relations"],
    academicYear: "2026/2027",
    officialUrl: "https://www.unimi.it/en",
    universitalyExternalId: "unimi-iple",
    dataConfidence: "MEDIUM",
    englishLevel: "B2",
    satMin: 1100,
    tuitionMin: 0,
    tuitionMax: 3900,
  },
  {
    universityName: "University of Bologna",
    universitySlug: "university-of-bologna",
    city: "Bologna",
    region: "Emilia-Romagna",
    website: "https://www.unibo.it",
    title: "Economics and Finance",
    slug: "economics-and-finance",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Economics",
    fieldTags: ["Economics", "Finance"],
    academicYear: "2027/2028",
    indicativeFromYear: "2026/2027",
    officialUrl: "https://www.unibo.it/en/study/degree-programmes",
    universitalyExternalId: "unibo-econ-fin",
    dataConfidence: "LOW",
    englishLevel: "B2",
    satMin: 1200,
    tuitionMin: 0,
    tuitionMax: 3500,
    notes: "2027/28 call not published — indicative from 2026/27.",
  },
  {
    universityName: "University of Padova",
    universitySlug: "university-of-padova",
    city: "Padova",
    region: "Veneto",
    website: "https://www.unipd.it",
    title: "Economics",
    slug: "economics-padova",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Economics",
    fieldTags: ["Economics", "Finance"],
    academicYear: "2027/2028",
    indicativeFromYear: "2026/2027",
    officialUrl: "https://www.unipd.it/en/",
    universitalyExternalId: "unipd-econ",
    dataConfidence: "LOW",
    englishLevel: "B2",
    satMin: 1200,
    notes: "2027/28 call not published — indicative from 2026/27. Do not treat prior deadline as current.",
  },
  {
    universityName: "University of Trento",
    universitySlug: "university-of-trento",
    city: "Trento",
    region: "Trentino-Alto Adige",
    website: "https://www.unitn.it",
    title: "Computer Science",
    slug: "computer-science-trento",
    degreeLevel: "BACHELOR",
    language: "English",
    field: "Computer Science",
    fieldTags: ["Computer Science", "AI"],
    academicYear: "2027/2028",
    indicativeFromYear: "2026/2027",
    officialUrl: "https://www.unitn.it/en",
    universitalyExternalId: "unitn-cs",
    dataConfidence: "LOW",
    englishLevel: "B2",
  },
];
